### ISSUE TITLE
Confusing repo

### ISSUE THREAD

**Issue by Paul-Reed** [TrystanLea/STM32Dev#5]
For anyone new wishing to contribute to developing this, the repo is confusing, which is the current work flow - [dBC_txshield_demo](https://github.com/TrystanLea/STM32Dev/tree/master/dBC_txshield_demo),[ STM01](https://github.com/TrystanLea/STM32Dev/tree/master/STM01), [STM02](https://github.com/TrystanLea/STM32Dev/tree/master/STM02)? or [pb66's repo](https://github.com/stm32oem/stm32tests)? 

Paul

**Comment by TrystanLea** [comment]
Hello Paul, dont think that's quite fair, this is my stm32dev notes repo, for sharing what Im doing with you guys! :)

**Comment by Paul-Reed** [comment]
I'm not wishing to sound unfair or rude, it's just an observation, that because there different versions of the build in the same repo (with no versioning), it's not clear which is the current version that is being developed, or which has your focus.
But you are right, it's your repo, and you can structure it as you wish.

**Comment by TrystanLea** [comment]
Thanks Paul, Im sure I/we will move to an openenergymonitor located repo once this becomes something beyond early development :)
